export enum RaftState {
  FOLLOWER = "follower",
  CANDIDATE = "candidate",
  LEADER = "leader",
}

export enum RaftEventType {
  STATE_CHANGE = "state_change",
  LEADER_ELECTED = "leader_elected",
  VOTE_GRANTED = "vote_granted",
  VOTE_DENIED = "vote_denied",
  LOG_REPLICATED = "log_replicated",
  HEARTBEAT_RECEIVED = "heartbeat_received",
  ELECTION_TIMEOUT = "election_timeout",
  CONFIGURATION_CHANGED = "configuration_changed",
  SNAPSHOT_CREATED = "snapshot_created",
  ERROR_OCCURRED = "error_occurred",
  METRICS_UPDATED = "metrics_updated",
  PEER_DISCOVERED = "peer_discovered",
  PEER_LOST = "peer_lost",
  INSTALL_SNAPSHOT = "install_snapshot",
  INSTALL_SNAPSHOT_RESPONSE = "install_snapshot_response",
  APPEND_ENTRIES = "append_entries",
  APPEND_ENTRIES_RESPONSE = "append_entries_response",
  VOTE_REQUEST = "vote_request",
  VOTE_RESPONSE = "vote_response",
  HEARTBEAT = "heartbeat",
  HEARTBEAT_RESPONSE = "heartbeat_response",
  CONFIGURATION_REQUEST = "configuration_request",
  CONFIGURATION_RESPONSE = "configuration_response",
  REPLICATION_FAILURE = "replication_failure",
  REPLICATION_SUCCESS = "replication_success",
  SNAPSHOT_REQUEST = "snapshot_request",
  SNAPSHOT_RESPONSE = "snapshot_response",
  LOG_COMPACTED = "log_compacted",
  LOG_TRUNCATED = "log_truncated",
  NODE_JOINED = "node_joined",
  NODE_LEFT = "node_left",
  METRICS_COLLECTED = "metrics_collected",
  HEARTBEAT_TIMEOUT = "heartbeat_timeout",
  CONFIGURATION_UPDATE = "configuration_update",
  ELECTION_STARTED = "election_started",
  ELECTION_ENDED = "election_ended",
  REPLICATION_STARTED = "replication_started",
  REPLICATION_ENDED = "replication_ended",
  SNAPSHOT_STARTED = "snapshot_started",
  SNAPSHOT_ENDED = "snapshot_ended",
  INSTALL_SNAPSHOT_STARTED = "install_snapshot_started",
  INSTALL_SNAPSHOT_ENDED = "install_snapshot_ended",
  INSTALL_SNAPSHOT_FAILED = "install_snapshot_failed",
  INSTALL_SNAPSHOT_SUCCESS = "install_snapshot_success",
  VOTE_REQUEST_RECEIVED = "vote_request_received",
  VOTE_RESPONSE_RECEIVED = "vote_response_received",
  APPEND_ENTRIES_RECEIVED = "append_entries_received",
  APPEND_ENTRIES_RESPONSE_RECEIVED = "append_entries_response_received",
  CONFIGURATION_REQUEST_RECEIVED = "configuration_request_received",
  CONFIGURATION_RESPONSE_RECEIVED = "configuration_response_received",
  SNAPSHOT_REQUEST_RECEIVED = "snapshot_request_received",
}

export enum LogLevel {
  DEBUG = "debug",
  INFO = "info",
  WARN = "warn",
  ERROR = "error",
  FATAL = "fatal",
}

export enum MessageType {
  VOTE_REQUEST = "vote_request",
  VOTE_RESPONSE = "vote_response",
  APPEND_ENTRIES = "append_entries",
  APPEND_ENTRIES_RESPONSE = "append_entries_response",
  INSTALL_SNAPSHOT = "install_snapshot",
  INSTALL_SNAPSHOT_RESPONSE = "install_snapshot_response",
}
